
services:
    bitcoin:
        image: bitcoin/bitcoin:30.0
        container_name: bitcoind
        ports:
          - "8333:8333"
        volumes:
            - bitcoin_data:/home/bitcoin/.bitcoin
        environment:
          - UID=1000
          - GID=1000
        command: ["-printtoconsole", "-rpcbind=0.0.0.0", "-rpcallowip=0.0.0.0/0", "-txindex=1"]

    electrs:
      image: 4324363/electrs:v0.10.8-arm64
      container_name: electrs
      user: "root"
      command: ["/usr/bin/electrs"] 
      ports:
        - "50001:50001" # For the electrs API on mainnet
      volumes:
        - electrs_data:/home/bitcoin
        - bitcoin_data:/home/bitcoin/.bitcoin:ro
      environment:
          - ELECTRS_DAEMON_DIR=/home/bitcoin/.bitcoin/ # Specify the directory since running in testnet mode we will have a different dir structure
          - ELECTRS_DAEMON_RPC_ADDR=bitcoin:8332 # Need to match the port as well
          - ELECTRS_DAEMON_P2P_ADDR=bitcoin:8333 # Need to match the port as well
          - ELECTRS_DAEMON_RPC_COOKIE=/home/bitcoin/.bitcoin/.cookie # Need to match the cookie file
          - ELECTRS_DB_DIR=/home/bitcoin/db
          - ELECTRS_ELECTRUM_RPC_ADDR=electrs:50001
          - ELECTRS_MONITORING_ADDR=electrs:4224
      depends_on:
        - bitcoin

    web:
      environment:
        FRONTEND_HTTP_PORT: "8080"
        BACKEND_MAINNET_HTTP_HOST: "api"
      image: mempool/frontend:v3.2.1
      user: "1000:1000"
      restart: on-failure
      stop_grace_period: 1m
      command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
      ports:
        - "80:8080"

    api:
      environment:
        MEMPOOL_BACKEND: "electrum"
        ELECTRUM_HOST: electrs
        ELECTRUM_PORT: "50001"
        ELECTRUM_TLS: "false"
        CORE_RPC_HOST: bitcoin
        CORE_RPC_PORT: "8332"
        CORE_RPC_COOKIE: "true"
        CORE_RPC_COOKIE_PATH: "/home/bitcoin/.bitcoin/.cookie"
        DATABASE_ENABLED: "true"
        DATABASE_HOST: "db"
        DATABASE_DATABASE: "mempool"
        DATABASE_USERNAME: "mempool"
        DATABASE_PASSWORD: "mempool"
        STATISTICS_ENABLED: "true"
        MEMPOOL_POLL_RATE_MS: "20000" # Optimized CPU load from 100% to 20%
      image: mempool/backend:v3.2.1
      user: "root"
      restart: on-failure
      stop_grace_period: 1m
      command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
      volumes:
        - mempool_data:/backend/cache
        - bitcoin_data:/home/bitcoin/.bitcoin:ro


    db:
      environment:
        MYSQL_DATABASE: "mempool"
        MYSQL_USER: "mempool"
        MYSQL_PASSWORD: "mempool"
        MYSQL_ROOT_PASSWORD: "admin"
      image: mariadb
      user: "root"
      restart: on-failure
      stop_grace_period: 1m
      volumes:
        - mempool_db:/var/lib/mysql

    grafana:
      image: grafana/grafana:latest
      restart: always
      ports:
        - 3000:3000
      volumes:
        - grafana_data:/var/lib/grafana

    prometheus:
      image: prom/prometheus:latest
      restart: always
      ports:
        - 9090:9090
      volumes:
        - prometheus_data:/prometheus
        - ./prometheus/:/etc/prometheus/
      command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      depends_on:
        - node_exporter

    node_exporter:
      image: prom/node-exporter:latest
      restart: always
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro

    json_exporter:
      image: quay.io/prometheuscommunity/json-exporter:latest
      restart: always
      ports:
        - 7979:7979
      command:
        - '--config.file=/config.yml'
      volumes:
        - ./bitaxe/json_exporter/config.yml:/config.yml

    cadvisor:
      image: gcr.io/cadvisor/cadvisor:latest
      container_name: cadvisor
      volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

    public-pool:
      image: 4324363/public-pool:arm64
      restart: always
      volumes:
        - bitcoin_data:/data/.bitcoin:ro
        - ./public-pool/.env:/public-pool/.env
      ports:
        - 3333:3333
        - 3334:3334

volumes:
    bitcoin_data:
    electrs_data:
    mempool_data:
    mempool_db:
    grafana_data:
    prometheus_data:
